import {useEffect,useState} from 'react';
import {Shield,ShieldAlert,FileSearch,RefreshCw,Clock,Check,AlertTriangle} from 'lucide-react';
type FileResult={name:string;size:number;sha256:string|null;status:string;scannedAt:number|null;findings:string[]};
type Report={protection?:{fresh:boolean;checkedAt:number|null;checks:Record<string,boolean>;reason:string};downloads?:{fresh:boolean;checkedAt:number|null;state:string;message:string;files:FileResult[];scope?:string;engine?:{available:boolean;version:string;definitionsAt:number|null;definitionsFresh:boolean}}};
const stamp=(value:number|null|undefined)=>value?new Date(value).toLocaleString():'Unavailable';
export default function SecurityDashboard({request,connected,hasSession}:{request:(path:string,method?:string)=>Promise<unknown>;connected:boolean;hasSession:boolean}){
  const [report,setReport]=useState<Report|null>(null),[error,setError]=useState(''),[queued,setQueued]=useState(false),[working,setWorking]=useState(false),[now,setNow]=useState(Date.now());
  async function refresh(){try{setReport(await request('/security') as Report);setError('')}catch(e){setError(e instanceof Error?e.message:'Could not read security status.')}}
  useEffect(()=>{if(!connected)return;void refresh();const timer=setInterval(()=>{setNow(Date.now());void refresh()},15000);return()=>clearInterval(timer)},[connected]);
  async function rescan(){setWorking(true);try{await request('/security/rescan','POST');setQueued(true);await refresh()}catch(e){setError(e instanceof Error?e.message:'Could not queue scan.')}finally{setWorking(false)}}
  const protection=report?.protection,downloads=report?.downloads;
  const fresh=!!protection?.fresh&&!!protection.checkedAt&&now-protection.checkedAt<45000;
  const scanFresh=!!downloads?.fresh&&!!downloads.checkedAt&&now-downloads.checkedAt<180000;
  const files=downloads?.files||[];
  const flagged=files.filter(f=>f.status==='flagged'||f.findings.length>0).length;
  const unresolved=files.filter(f=>['pending','not_scanned','error'].includes(f.status)).length;
  return <main className="workspace dashboard-page">
    <div className="heading"><div><div className="eyebrow">LIVE SECURITY</div><h1>Know what’s happening.</h1><p>Operational checks and local download scanning for your current session. Results describe a point in time, not a guarantee of safety.</p></div><button className="control-button" onClick={()=>void refresh()} disabled={!connected}><RefreshCw size={16}/>Refresh status</button></div>
    <div className="security-metrics"><article><Shield size={22}/><span>Network checks</span><strong>{fresh&&Object.values(protection?.checks||{}).every(Boolean)?'Passing':fresh?'Needs attention':'Unavailable'}</strong><small>{stamp(protection?.checkedAt)}</small></article><article><FileSearch size={22}/><span>Download monitor</span><strong>{scanFresh?downloads?.state==='scanning'?'Scanning':downloads?.state==='idle'?'Ready for a session':downloads?.state==='monitoring'?'Monitoring':'Needs attention':'Unavailable'}</strong><small>Downloads folder only</small></article><article><ShieldAlert size={22}/><span>Files to review</span><strong>{scanFresh?flagged:'—'}</strong><small>{scanFresh?`${unresolved} pending, skipped, or failed`:'Waiting for a current report'}</small></article></div>
    <section className="dashboard-card"><div className="card-heading"><h2>Isolation & connection</h2><span>Checked independently of the browser</span></div><div className="check-grid">{[['firewall','Network rules','Matches the reviewed firewall baseline.'],['routing','VPN-only route','Includes the fail-closed fallback route.'],['vpn','VPN connection','A recent WireGuard handshake was observed.'],['proxy','Display service','The isolated display proxy is available.']].map(([key,label,description])=><div key={key}><span className={fresh&&protection?.checks[key]?'check-icon pass':'check-icon warn'}>{fresh&&protection?.checks[key]?<Check size={18}/>:<AlertTriangle size={18}/>}</span><div><strong>{label}</strong><p>{description}</p><small>{fresh?(protection?.checks[key]?'Check passed':'Check failed'):'Unknown / stale'}</small></div></div>)}</div><p className="dashboard-note">{protection?.reason||'Connect to your Pi to read live checks.'}</p></section>
    <section className="dashboard-card"><div className="card-heading"><div><h2>Downloads</h2><p>{downloads?.message||'Waiting for download monitoring.'}</p></div><button className="control-button" onClick={rescan} disabled={!connected||!hasSession||working}><FileSearch size={16}/>{working?'Requesting…':'Scan again'}</button></div>
    {queued&&<p role="status" className="dashboard-note">Scan requested. The monitor checks every 30 seconds; large batches can take longer.</p>}
    <div className="engine-line"><span className={downloads?.engine?.available&&downloads.engine.definitionsFresh?'pass':'warn'}>{downloads?.engine?.available?'ClamAV installed':'Antivirus unavailable'} · {downloads?.engine?.definitionsFresh?'Definitions current':'Definitions missing or older than 48 hours'}</span><small>{downloads?.engine?.version||'Waiting for engine information'}</small></div>
    {files.length?<div className="download-list">{files.map((f,index)=><article className="download-row" key={f.name+index}><div className="download-title"><FileSearch size={19}/><strong>{f.name}</strong><span className={'result-badge '+(f.status==='flagged'?'danger':f.findings.length||f.status!=='no_detection'?'warn':'neutral')}>{f.status==='flagged'?'Flagged':f.status==='no_detection'?(f.findings.length?'Review file':'No detection'):f.status==='not_scanned'?'Not scanned':f.status==='error'?'Scan failed':'Pending'}</span></div><p>{(f.size/1024).toFixed(1)} KB · {f.scannedAt?'Scanned '+stamp(f.scannedAt):'No completed antivirus result'}</p>{f.findings.length>0&&<ul>{f.findings.map((item,i)=><li key={i}>{item}</li>)}</ul>}{f.sha256&&<details><summary>File fingerprint</summary><code>{f.sha256}</code></details>}</article>)}</div>:<div className="security-empty"><FileSearch size={32}/><h3>{hasSession?'No files reported yet':'No active session'}</h3><p>{hasSession?'Completed downloads appear here after the monitor collects them.':'Launch a browser or desktop, then download files into its Downloads folder.'}</p></div>}
    <p className="dashboard-note"><Clock size={14}/>Monitoring uses snapshots. It does not block a file from running or automatically delete it. Files over 32 MiB, batches over 128 MiB, and files beyond the first 100 may remain unscanned.</p><p className="dashboard-note">Downloads remain inside the isolated session. No files are sent to a third-party scanning service. An encrypted archive, scan error, or old definitions need review.</p></section>
    {error&&<p className="notice" role="alert">{error}</p>}
  </main>;
}
